sudo: false
language: python
cache: false

python:
  - "2.7"
  - "3.6"
env:
  - REQUESTS_VERSION="2.18.4"
  - REQUESTS_VERSION="2.19.1"
  - REQUESTS_VERSION="2.20.1"
  - REQUESTS_VERSION="2.21.0"
install:
  - bash install_dev_requests.sh "$REQUESTS_VERSION"
  - python setup.py -q install
stages:
  - test

jobs:
  include:
    - stage: test
      name: Advocate Tests
      script: bash .travis/test.sh
    - name: Requests Compliance Tests
      script: bash .travis/test_requests.sh

# Coverage metrics
before_install:
  - pip install codecov
after_success:
  - codecov
