sudo: false
language: python
cache: false

python:
  - "2.7"
  - "3.6"
env:
  - REQUESTS_VERSION="2.18.4"
  - REQUESTS_VERSION="2.19.1"
  - REQUESTS_VERSION="2.20.1"
  - REQUESTS_VERSION="2.21.0"
install:
  - bash install_dev_requests.sh "$REQUESTS_VERSION"
  - python setup.py -q install

script: bash .travis/all_tests.sh

# Coverage metrics
before_install:
  - pip install codecov
after_success:
  - codecov
